#ifndef __PINMAP_H__
#define __PINMAP_H__

#define BOARD_CS2F103C8T6_QG

#define AT24C02_SCL_PIN  GPIOB, GPIO_PIN_4
#define AT24C02_SDA_PIN  GPIOB, GPIO_PIN_6

#define LED_PIN          GPIOA, GPIO_PIN_1
#define KEY_PIN          GPIOA, GPIO_PIN_8

#define NRF24L01_IRQ_PIN GPIOA, GPIO_PIN_15
#define NRF24L01_CS_PIN  GPIOB, GPIO_PIN_2
#define NRF24L01_CE_PIN  GPIOB, GPIO_PIN_0

#define FLASH_CS_PIN     GPIOC, GPIO_PIN_13
#define TFCARD_CS_PIN    GPIOA, GPIO_PIN_4

#define LCD_SCL_PIN      GPIOB, GPIO_PIN_1
#define LCD_SDA_PIN      GPIOB, GPIO_PIN_3
#define LCD_RES_PIN      GPIOB, GPIO_PIN_5
#define LCD_DC_PIN       GPIOB, GPIO_PIN_7
#define LCD_CS_PIN       GPIOB, GPIO_PIN_9
#define LCD_BL_PIN       GPIOB, GPIO_PIN_11

#define SPI_NSS          GPIOA, GPIO_PIN_5
#define SPI_MOSI         GPIOA, GPIO_PIN_7
#define SPI_MISO         GPIOA, GPIO_PIN_6

#endif
