#include "paraattr.h"

// clang-format off
const para_attr_t sDeviceAttr[] = {
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0000 u32DrvSchemeWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0000 u32DrvSchemeWH
    {           WL(0),           WL(0),           WL(0),    B_RO | B_RL_UP | B_NSYNC | B_NCOV | B_DOB0 }, // P0002 u32McuSwBuildDateWL
    {           WH(0),           WH(0),           WH(0),    B_RO | B_RL_UP | B_NSYNC | B_NCOV | B_DOB1 }, // P0002 u32McuSwBuildDateWH
    {           WL(0),           WL(0),           WL(0),    B_RO | B_RL_DN | B_NSYNC | B_NCOV | B_DOB0 }, // P0004 u32McuSwBuildTimeWL
    {           WH(0),           WH(0),           WH(0),    B_RO | B_RL_DN | B_NSYNC | B_NCOV | B_DOB1 }, // P0004 u32McuSwBuildTimeWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_RL | B_NSYNC | B_NCOV | B_DOB0 }, // P0006 u32McuSwVerWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_RL | B_NSYNC | B_NCOV | B_DOB1 }, // P0006 u32McuSwVerWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0008 _Resv8
    {            W(1),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0009 u16AxisNum
    {            W(2),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0010 u16LedNum
    {            W(3),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0011 u16KeyNum
    {            W(2),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0012 u16ExtDiNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0013 u16ExtDoNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0014 u16ExtHDiNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0015 u16ExtHDoNum
    {            W(2),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0016 u16ExtAiNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0017 u16ExtAoNum
    {            W(1),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0018 u16TsNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0019 _Resv19
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0020 u32ChipDevIDWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0020 u32ChipDevIDWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0022 u32ChipRevIDWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0022 u32ChipRevIDWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0024 u32ChipUIDw0WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0024 u32ChipUIDw0WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0026 u32ChipUIDw1WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0026 u32ChipUIDw1WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0028 u32ChipUIDw2WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0028 u32ChipUIDw2WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0030 u32HalVersionWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0030 u32HalVersionWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0032 _Resv32
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0033 u16SysPwd
    {            W(0),            W(0),            W(2),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0034 u16SysAccess
    {            W(0),            W(0),            W(1), B_RW_M2 |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0035 u16SysRst
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0036 _Resv36
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0037 u16UmdcHwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0038 u16UcdcHwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0039 u16Uai0HwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0040 u16Uai1HwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0041 u16Uai2HwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0042 u16UTempHwCoeff
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0043 _Resv43
    {            W(1),            W(1),          W(247), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0044 u16MbSlvId
    {       WL(19200),           WL(0),     WL(1000000), B_RW_M1 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0045 u32MbBaudrateWL
    {       WH(19200),           WH(0),     WH(1000000), B_RW_M1 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0045 u32MbBaudrateWH
    {            W(2),            W(0),            W(2), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0047 u16MbParity
    {            W(0),            W(0),            W(1), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0048 u16MbMstEndian
    {         W(5000),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0049 u16MbDisconnTime
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0050 u16MbResponseDelay
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0051 _Resv51
    {            W(1),            W(1),          W(127), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0052 u16CopNodeId
    {            W(0),            W(0),            W(0), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0053 u16CopBitrate
    {          W(100),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0054 u16PdoInhTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0055 u16CopState
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0056 _Resv56
    {            W(2),            W(1),         W(1000), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0057 u16EcatScanPrd
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0058 u16EcatState
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0059 u16EcatPort0ErrCnt
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0060 u16EcatPort1ErrCnt
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0061 u16EcatRxErrCnt
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0062 u16EcatPdiErrCnt
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0063 _Resv63
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0064 _Resv64
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0065 _Resv65
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0066 u16ScopeSampPrd
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0067 u16ScopeSampPts
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0068 u16ScopeChCnt
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0069 u16ScopeChSrc00
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0070 u16ScopeChSrc01
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0071 u16ScopeChSrc02
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0072 u16ScopeChSrc03
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0073 u16ScopeChSrc04
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0074 u16ScopeChSrc05
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0075 u16ScopeChSrc06
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0076 u16ScopeChSrc07
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0077 u16ScopeChAddr00
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0078 u16ScopeChAddr01
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0079 u16ScopeChAddr02
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0080 u16ScopeChAddr03
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0081 u16ScopeChAddr04
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0082 u16ScopeChAddr05
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0083 u16ScopeChAddr06
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0084 u16ScopeChAddr07
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0085 u16ScopeSampIdx
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0086 u16ScopeSampSts
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0087 _Resv87
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0088 _Resv88
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0089 _Resv89
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0090 _Resv90
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0091 _Resv91
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0092 _Resv92
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0093 _Resv93
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0094 _Resv94
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0095 _Resv95
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0096 _Resv96
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0097 _Resv97
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0098 _Resv98
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0099 _Resv99
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0100 _Resv100
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0101 _Resv101
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0102 _Resv102
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0103 _Resv103
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0104 _Resv104
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0105 _Resv105
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0106 _Resv106
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0107 _Resv107
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0108 _Resv108
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0109 _Resv109
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0110 _Resv110
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0111 _Resv111
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0112 _Resv112
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0113 _Resv113
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0114 _Resv114
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0115 _Resv115
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0116 _Resv116
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0117 _Resv117
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0118 _Resv118
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0119 _Resv119
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0120 _Resv120
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0121 _Resv121
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0122 _Resv122
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0123 _Resv123
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0124 _Resv124
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0125 _Resv125
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0126 _Resv126
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0127 _Resv127
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0128 _Resv128
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0129 _Resv129
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0130 _Resv130
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0131 _Resv131
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0132 _Resv132
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0133 _Resv133
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0134 _Resv134
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0135 _Resv135
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0136 _Resv136
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0137 _Resv137
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0138 _Resv138
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0139 _Resv139
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0140 _Resv140
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0141 _Resv141
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0142 _Resv142
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0143 _Resv143
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0144 _Resv144
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0145 _Resv145
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0146 _Resv146
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0147 _Resv147
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0148 _Resv148
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0149 _Resv149
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0150 _Resv150
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0151 _Resv151
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0152 _Resv152
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0153 _Resv153
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0154 _Resv154
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0155 _Resv155
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0156 _Resv156
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0157 _Resv157
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0158 _Resv158
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0159 _Resv159
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0160 _Resv160
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0161 _Resv161
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0162 _Resv162
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0163 _Resv163
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0164 _Resv164
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0165 _Resv165
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0166 _Resv166
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0167 _Resv167
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0168 _Resv168
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0169 _Resv169
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0170 _Resv170
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0171 _Resv171
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0172 _Resv172
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0173 _Resv173
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0174 _Resv174
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0175 _Resv175
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0176 _Resv176
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0177 _Resv177
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0178 _Resv178
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0179 _Resv179
    {        W(22096),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0180 u16TunerSoftVer
    {       W(0x0303),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0181 u16TunerDrvType
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0182 _Resv182
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0183 _Resv183
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0184 u16AlmCode01
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0185 u16AlmCode02
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0186 u16AlmCode03
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0187 u16AlmCode04
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0188 u16AlmCode05
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0189 u16AlmCode06
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0190 u16AlmCode07
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0191 u16AlmCode08
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0192 u16AlmCode09
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0193 u16AlmCode10
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0194 u16AlmCode11
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0195 u16AlmCode12
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0196 u16AlmCode13
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0197 u16AlmCode14
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0198 u16AlmCode15
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0199 u32AlmTime00WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0199 u32AlmTime00WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0201 u32AlmTime01WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0201 u32AlmTime01WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0203 u32AlmTime02WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0203 u32AlmTime02WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0205 u32AlmTime03WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0205 u32AlmTime03WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0207 u32AlmTime04WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0207 u32AlmTime04WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0209 u32AlmTime05WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0209 u32AlmTime05WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0211 u32AlmTime06WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0211 u32AlmTime06WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0213 u32AlmTime07WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0213 u32AlmTime07WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0215 u32AlmTime08WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0215 u32AlmTime08WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0217 u32AlmTime09WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0217 u32AlmTime09WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0219 u32AlmTime10WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0219 u32AlmTime10WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0221 u32AlmTime11WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0221 u32AlmTime11WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0223 u32AlmTime12WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0223 u32AlmTime12WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0225 u32AlmTime13WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0225 u32AlmTime13WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0227 u32AlmTime14WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0227 u32AlmTime14WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0229 u32AlmTime15WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0229 u32AlmTime15WH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0231 _Resv231
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0232 _Resv232
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0233 u32SysRunTimeWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0233 u32SysRunTimeWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0235 _Resv235
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0236 _Resv236
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0237 u16DiState
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0238 u16DoState
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0239 _Resv239
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0240 s16UaiPu0
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0241 s16UaiPu1
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0242 s16UaiPu2
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0243 _Resv243
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0244 s16UaiSi0
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0245 s16UaiSi1
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0246 s16UaiSi2
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0247 u16UaoSi0
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0248 u16UaoSi1
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0249 u16UaoSi2
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0250 _Resv250
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0251 _Resv251
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0252 u16UmdcSi
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0253 u16UcdcSi
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0254 s16TempIpmSi
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0255 s16TempRectSi
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0256 _Resv256
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0257 _Resv257
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0258 _Resv258
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0259 _Resv259
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0260 _Resv260
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0261 u16ProbeStatus
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0262 s64ProbePosEdgePo00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0262 s64ProbePosEdgePo00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0262 s64ProbePosEdgePo00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0262 s64ProbePosEdgePo00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0266 s64ProbeNegEdgePo00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0266 s64ProbeNegEdgePo00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0266 s64ProbeNegEdgePo00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0266 s64ProbeNegEdgePo00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0270 s64ProbePosEdgePo01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0270 s64ProbePosEdgePo01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0270 s64ProbePosEdgePo01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0270 s64ProbePosEdgePo01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0274 s64ProbeNegEdgePo01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0274 s64ProbeNegEdgePo01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0274 s64ProbeNegEdgePo01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0274 s64ProbeNegEdgePo01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0278 s64ProbePosEdgePo02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0278 s64ProbePosEdgePo02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0278 s64ProbePosEdgePo02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0278 s64ProbePosEdgePo02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0282 s64ProbeNegEdgePo02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0282 s64ProbeNegEdgePo02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0282 s64ProbeNegEdgePo02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0282 s64ProbeNegEdgePo02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0286 s64ProbePosEdgePo03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0286 s64ProbePosEdgePo03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0286 s64ProbePosEdgePo03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0286 s64ProbePosEdgePo03W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0290 s64ProbeNegEdgePo03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0290 s64ProbeNegEdgePo03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0290 s64ProbeNegEdgePo03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0290 s64ProbeNegEdgePo03W3
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0294 _Resv294
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0295 _Resv295
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0296 u16PosLoopIsrTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0297 u16SpdLoopIsrTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0298 u16CurLoopIsrTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0299 u16LoopTick
};

const para_attr_t sAxisAttr[] = {
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0300 _Resv300
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0301 u16MotorType
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0302 u16EncoderType
    {            W(2),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0303 u16MotPolePairs
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0304 u16MotAccMax
    {           WL(0),           WL(0),     WL(U32_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV | B_DOB0 }, // P0305 u32MotInertiaWL
    {           WH(0),           WH(0),     WH(U32_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV | B_DOB1 }, // P0305 u32MotInertiaWH
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0307 u16MotStatorRes
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0308 u16MotStatorLd
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0309 u16MotStatorLq
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0310 u16MotCurRate
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0311 u16MotCurMax
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0312 u16MotTrqRate
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0313 u16MotTrqMax
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0314 u16MotSpdRate
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0315 u16MotSpdMax
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0316 u16MotEmfCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0317 u16MotTrqCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0318 u16MotTm
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0319 _Resv319
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0320 u16EncWorkMode
    {            W(6),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0321 u16EncRes
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0322 u32EncPosInitWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0322 u32EncPosInitWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0324 u16EncPos
    {           W0(0),           W0(0),           W0(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0325 s64EncMultPosW0
    {           W1(0),           W1(0),           W1(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0325 s64EncMultPosW1
    {           W2(0),           W2(0),           W2(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0325 s64EncMultPosW2
    {           W3(0),           W3(0),           W3(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0325 s64EncMultPosW3
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0329 s32EncTurnsWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0329 s32EncTurnsWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0331 _Resv331
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0332 u16HallState
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0333 _Resv333
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0334 u16CurSampType
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0335 u16PwmDutyMax
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0336 _Resv336
    {         W(8000),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0337 u16CarryFreq
    {         W(8000),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0338 u16PosLoopFreq
    {         W(8000),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0339 u16SpdLoopFreq
    {         W(4000),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0340 u16CurLoopFreq
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0341 _Resv341
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0342 _Resv342
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0343 _Resv343
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0344 _Resv344
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0345 _Resv345
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0346 u16PosLoopKp
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0347 u16PosLoopKi
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0348 u16PosLoopKd
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0349 u16SpdLoopKp
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0350 u16SpdLoopKi
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0351 u16SpdLoopKd
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0352 u16CurLoopIqKp
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0353 u16CurLoopIqKi
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0354 u16CurLoopIqKd
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0355 u16CurLoopIdKp
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0356 u16CurLoopIdKi
    {            W(0),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0357 u16CurLoopIdKd
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0358 _Resv358
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0359 _Resv359
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0360 _Resv360
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0361 _Resv361
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0362 _Resv362
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0363 _Resv363
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0364 _Resv364
    {            W(1),            W(0),            W(3), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0365 u16AppSel
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0366 u16CtrlMethod
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0367 u16CtrlMode
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0368 u16CtrlCmdSrc
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0369 u16PwrOnAutoRun
    {           WL(0),     WL(U32_MIN),     WL(U32_MAX), B_RW_M0 |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0370 u32CommCmdWL
    {           WH(0),     WH(U32_MIN),     WH(U32_MAX), B_RW_M0 |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0370 u32CommCmdWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0372 _Resv372
    {            W(0),            W(0),            W(1), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0373 u16DiSrc
    {            W(0),            W(0),            W(1), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0374 u16DoSrc
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0375 _Resv375
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0376 _Resv376
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0377 u16PosLimSrc
    {           W0(0),           W0(0),           W0(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0378 s64PosLimFwdW0
    {           W1(0),           W1(0),           W1(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0378 s64PosLimFwdW1
    {           W2(0),           W2(0),           W2(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0378 s64PosLimFwdW2
    {           W3(0),           W3(0),           W3(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0378 s64PosLimFwdW3
    {           W0(0),           W0(0),           W0(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0382 s64PosLimRevW0
    {           W1(0),           W1(0),           W1(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0382 s64PosLimRevW1
    {           W2(0),           W2(0),           W2(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0382 s64PosLimRevW2
    {           W3(0),           W3(0),           W3(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0382 s64PosLimRevW3
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0386 u16PosLimSts
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0387 _Resv387
    {           WL(0),           WL(0),           WL(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0388 u32ElecGearNumWL
    {           WH(0),           WH(0),           WH(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0388 u32ElecGearNumWH
    {           WL(0),           WL(0),           WL(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0390 u32ElecGearDenoWL
    {           WH(0),           WH(0),           WH(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0390 u32ElecGearDenoWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0392 _Resv392
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0393 u16EncFreqDivDir
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0394 u16EncFreqDivNum
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0395 u16EncFreqDivDeno
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0396 _Resv396
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0397 s64PosDigRef00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0397 s64PosDigRef00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0397 s64PosDigRef00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0397 s64PosDigRef00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0401 s64PosDigRef01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0401 s64PosDigRef01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0401 s64PosDigRef01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0401 s64PosDigRef01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0405 s64PosDigRef02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0405 s64PosDigRef02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0405 s64PosDigRef02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0405 s64PosDigRef02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0409 s64PosDigRef03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0409 s64PosDigRef03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0409 s64PosDigRef03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0409 s64PosDigRef03W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0413 s64PosDigRef04W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0413 s64PosDigRef04W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0413 s64PosDigRef04W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0413 s64PosDigRef04W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0417 s64PosDigRef05W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0417 s64PosDigRef05W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0417 s64PosDigRef05W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0417 s64PosDigRef05W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0421 s64PosDigRef06W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0421 s64PosDigRef06W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0421 s64PosDigRef06W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0421 s64PosDigRef06W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0425 s64PosDigRef07W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0425 s64PosDigRef07W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0425 s64PosDigRef07W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0425 s64PosDigRef07W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0429 s64PosDigRef08W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0429 s64PosDigRef08W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0429 s64PosDigRef08W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0429 s64PosDigRef08W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0433 s64PosDigRef09W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0433 s64PosDigRef09W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0433 s64PosDigRef09W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0433 s64PosDigRef09W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0437 s64PosDigRef10W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0437 s64PosDigRef10W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0437 s64PosDigRef10W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0437 s64PosDigRef10W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0441 s64PosDigRef11W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0441 s64PosDigRef11W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0441 s64PosDigRef11W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0441 s64PosDigRef11W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0445 s64PosDigRef12W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0445 s64PosDigRef12W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0445 s64PosDigRef12W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0445 s64PosDigRef12W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0449 s64PosDigRef13W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0449 s64PosDigRef13W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0449 s64PosDigRef13W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0449 s64PosDigRef13W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0453 s64PosDigRef14W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0453 s64PosDigRef14W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0453 s64PosDigRef14W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0453 s64PosDigRef14W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0457 s64PosDigRef15W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0457 s64PosDigRef15W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0457 s64PosDigRef15W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0457 s64PosDigRef15W3
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0461 _Resv461
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0462 u16ProbeStatus
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0463 s64ProbePosEdgePo00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0463 s64ProbePosEdgePo00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0463 s64ProbePosEdgePo00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0463 s64ProbePosEdgePo00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0467 s64ProbeNegEdgePo00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0467 s64ProbeNegEdgePo00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0467 s64ProbeNegEdgePo00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0467 s64ProbeNegEdgePo00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0471 s64ProbePosEdgePo01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0471 s64ProbePosEdgePo01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0471 s64ProbePosEdgePo01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0471 s64ProbePosEdgePo01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0475 s64ProbeNegEdgePo01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0475 s64ProbeNegEdgePo01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0475 s64ProbeNegEdgePo01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0475 s64ProbeNegEdgePo01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0479 s64ProbePosEdgePo02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0479 s64ProbePosEdgePo02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0479 s64ProbePosEdgePo02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0479 s64ProbePosEdgePo02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0483 s64ProbeNegEdgePo02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0483 s64ProbeNegEdgePo02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0483 s64ProbeNegEdgePo02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0483 s64ProbeNegEdgePo02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0487 s64ProbePosEdgePo03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0487 s64ProbePosEdgePo03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0487 s64ProbePosEdgePo03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0487 s64ProbePosEdgePo03W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0491 s64ProbeNegEdgePo03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0491 s64ProbeNegEdgePo03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0491 s64ProbeNegEdgePo03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0491 s64ProbeNegEdgePo03W3
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0495 _Resv495
    {            W(0),            W(0),            W(1), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0496 u16SpdRefSrc
    {           WL(0),           WL(0),           WL(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0497 s32SpdDigRefWL
    {           WH(0),           WH(0),           WH(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0497 s32SpdDigRefWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0499 _Resv499
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0500 u16AccTime
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0501 u16DecTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0502 _Resv502
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0503 u16JogDigRef
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0504 u16JogAccDecTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0505 _Resv505
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0506 u16SpdLimSrc
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0507 u16SpdLimFwd
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0508 u16SpdLimRev
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0509 u16SpdLimSts
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0510 _Resv510
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0511 u16AiSpdCoeff00
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0512 u16AiSpdCoeff01
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0513 u16AiSpdCoeff02
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0514 _Resv514
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0515 _Resv515
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0516 _Resv516
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0517 _Resv517
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0518 _Resv518
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0519 _Resv519
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0520 _Resv520
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0521 _Resv521
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0522 s32SpdDigRef00WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0522 s32SpdDigRef00WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0524 s32SpdDigRef01WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0524 s32SpdDigRef01WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0526 s32SpdDigRef02WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0526 s32SpdDigRef02WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0528 s32SpdDigRef03WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0528 s32SpdDigRef03WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0530 s32SpdDigRef04WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0530 s32SpdDigRef04WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0532 s32SpdDigRef05WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0532 s32SpdDigRef05WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0534 s32SpdDigRef06WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0534 s32SpdDigRef06WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0536 s32SpdDigRef07WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0536 s32SpdDigRef07WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0538 s32SpdDigRef08WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0538 s32SpdDigRef08WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0540 s32SpdDigRef09WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0540 s32SpdDigRef09WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0542 s32SpdDigRef10WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0542 s32SpdDigRef10WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0544 s32SpdDigRef11WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0544 s32SpdDigRef11WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0546 s32SpdDigRef12WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0546 s32SpdDigRef12WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0548 s32SpdDigRef13WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0548 s32SpdDigRef13WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0550 s32SpdDigRef14WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0550 s32SpdDigRef14WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0552 s32SpdDigRef15WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0552 s32SpdDigRef15WH
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0554 u16AccTime00
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0555 u16AccTime01
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0556 u16AccTime02
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0557 u16AccTime03
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0558 u16AccTime04
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0559 u16AccTime05
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0560 u16AccTime06
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0561 u16AccTime07
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0562 u16AccTime08
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0563 u16AccTime09
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0564 u16AccTime10
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0565 u16AccTime11
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0566 u16AccTime12
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0567 u16AccTime13
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0568 u16AccTime14
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0569 u16AccTime15
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0570 u16DecTime00
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0571 u16DecTime01
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0572 u16DecTime02
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0573 u16DecTime03
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0574 u16DecTime04
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0575 u16DecTime05
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0576 u16DecTime06
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0577 u16DecTime07
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0578 u16DecTime08
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0579 u16DecTime09
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0580 u16DecTime10
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0581 u16DecTime11
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0582 u16DecTime12
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0583 u16DecTime13
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0584 u16DecTime14
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0585 u16DecTime15
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0586 _Resv586
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0587 _Resv587
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0588 _Resv588
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0589 _Resv589
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0590 _Resv590
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0591 _Resv591
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0592 s16TrqDigRef00
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0593 s16TrqDigRef01
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0594 s16TrqDigRef02
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0595 s16TrqDigRef03
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0596 s16TrqDigRef04
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0597 s16TrqDigRef05
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0598 s16TrqDigRef06
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0599 s16TrqDigRef07
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0600 s16TrqDigRef08
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0601 s16TrqDigRef09
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0602 s16TrqDigRef10
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0603 s16TrqDigRef11
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0604 s16TrqDigRef12
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0605 s16TrqDigRef13
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0606 s16TrqDigRef14
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0607 s16TrqDigRef15
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0608 _Resv608
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0609 _Resv609
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0610 _Resv610
    {            W(5),      W(U16_MIN),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0611 u16OpenPeriod
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0612 s16OpenElecAngInit
    {         W(1000),        W(-3000),         W(3000), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0613 s16OpenElecAngInc
    {        W(16000),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0614 s16OpenUdRef
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0615 s16OpenUqRef
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0616 _Resv616
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0617 _Resv617
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0618 _Resv618
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0619 _Resv619
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0620 _Resv620
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0621 _Resv621
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0622 _Resv622
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0623 _Resv623
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0624 _Resv624
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0625 u16AxisFSM
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0626 _Resv626
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0627 _Resv627
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0628 _Resv628
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0629 _Resv629
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0630 s32DrvSpdRefWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0630 s32DrvSpdRefWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0632 s32DrvSpdFbWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0632 s32DrvSpdFbWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0634 _Resv634
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0635 _Resv635
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0636 _Resv636
    {            W(0),      W(U16_MIN),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0637 u16ElecAngle
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0638 _Resv638
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0639 _Resv639
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0640 _Resv640
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0641 _Resv641
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0642 s16Ud
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0643 s16Uq
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0644 s16Ualpha
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0645 s16Ubeta
    {            W(0),            W(0),            W(7),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0646 u16Sector
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0647 u16PwmaComp
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0648 u16PwmbComp
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0649 u16PwmcComp
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0650 _Resv650
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0651 _Resv651
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0652 _Resv652
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0653 _Resv653
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0654 _Resv654
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0655 _Resv655
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0656 _Resv656
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0657 s16IaFbSi
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0658 s16IbFbSi
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0659 s16IcFbSi
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0660 _Resv660
    {           W0(0),           W0(0),           W0(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0661 s64UserPosRefW0
    {           W1(0),           W1(0),           W1(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0661 s64UserPosRefW1
    {           W2(0),           W2(0),           W2(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0661 s64UserPosRefW2
    {           W3(0),           W3(0),           W3(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0661 s64UserPosRefW3
    {           W0(0),           W0(0),           W0(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0665 s64UserPosFbW0
    {           W1(0),           W1(0),           W1(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0665 s64UserPosFbW1
    {           W2(0),           W2(0),           W2(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0665 s64UserPosFbW2
    {           W3(0),           W3(0),           W3(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0665 s64UserPosFbW3
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0669 s32UserSpdRefWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0669 s32UserSpdRefWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0671 s32UserSpdFbWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0671 s32UserSpdFbWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0673 s16UserTrqRef
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0674 s16UserTrqFb
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0675 _Resv675
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0676 _Resv676
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0677 _Resv677
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0678 _Resv678
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0679 _Resv679
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0680 _Resv680
};
// clang-format on
