#include "paraattr.h"

// clang-format off
const para_attr_t sDeviceAttr[] = {
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0000 u32DrvSchemeWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0000 u32DrvSchemeWH
    {           WL(0),           WL(0),           WL(0),    B_RO | B_RL_UP | B_NSYNC | B_NCOV | B_DOB0 }, // P0002 u32McuSwBuildDateWL
    {           WH(0),           WH(0),           WH(0),    B_RO | B_RL_UP | B_NSYNC | B_NCOV | B_DOB1 }, // P0002 u32McuSwBuildDateWH
    {           WL(0),           WL(0),           WL(0),    B_RO | B_RL_DN | B_NSYNC | B_NCOV | B_DOB0 }, // P0004 u32McuSwBuildTimeWL
    {           WH(0),           WH(0),           WH(0),    B_RO | B_RL_DN | B_NSYNC | B_NCOV | B_DOB1 }, // P0004 u32McuSwBuildTimeWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_RL | B_NSYNC | B_NCOV | B_DOB0 }, // P0006 u32McuSwVerWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_RL | B_NSYNC | B_NCOV | B_DOB1 }, // P0006 u32McuSwVerWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0008 _Resv8
    {            W(1),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0009 u16AxisNum
    {            W(2),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0010 u16LedNum
    {            W(3),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0011 u16KeyNum
    {            W(2),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0012 u16ExtDiNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0013 u16ExtDoNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0014 u16ExtHDiNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0015 u16ExtHDoNum
    {            W(2),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0016 u16ExtAiNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0017 u16ExtAoNum
    {            W(1),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0018 u16TsNum
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0019 _Resv19
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0020 u32ChipDevIDWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0020 u32ChipDevIDWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0022 u32ChipRevIDWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0022 u32ChipRevIDWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0024 u32ChipUIDw0WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0024 u32ChipUIDw0WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0026 u32ChipUIDw1WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0026 u32ChipUIDw1WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0028 u32ChipUIDw2WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0028 u32ChipUIDw2WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0030 u32HalVersionWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0030 u32HalVersionWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0032 _Resv32
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0033 u16SysPwd
    {            W(0),            W(0),            W(2),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0034 u16SysAccess
    {            W(0),            W(0),            W(1), B_RW_M2 |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0035 u16SysRst
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0036 u32SysRunTimeWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0036 u32SysRunTimeWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0038 _Resv38
    {            W(1),            W(1),          W(247), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0039 u16MbSlvId
    {       WL(19200),           WL(0),     WL(1000000), B_RW_M1 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0040 u32MbBaudrateWL
    {       WH(19200),           WH(0),     WH(1000000), B_RW_M1 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0040 u32MbBaudrateWH
    {            W(2),            W(0),            W(2), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0042 u16MbParity
    {            W(0),            W(0),            W(1), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0043 u16MbMstEndian
    {         W(5000),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0044 u16MbDisconnTime
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0045 u16MbResponseDelay
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0046 _Resv46
    {            W(1),            W(1),          W(127), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0047 u16CopNodeId
    {            W(0),            W(0),            W(0), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0048 u16CopBitrate
    {          W(100),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0049 u16PdoInhTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0050 u16CopState
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0051 _Resv51
    {            W(2),            W(1),         W(1000), B_RW_M1 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0052 u16EcatScanPrd
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0053 u16EcatState
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0054 u16EcatPort0ErrCnt
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0055 u16EcatPort1ErrCnt
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0056 u16EcatRxErrCnt
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0057 u16EcatPdiErrCnt
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0058 _Resv58
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0059 _Resv59
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0060 _Resv60
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0061 u16ScopeSampPrd
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0062 u16ScopeSampPts
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0063 u16ScopeChCnt
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0064 u16ScopeChSrc00
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0065 u16ScopeChSrc01
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0066 u16ScopeChSrc02
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0067 u16ScopeChSrc03
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0068 u16ScopeChSrc04
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0069 u16ScopeChSrc05
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0070 u16ScopeChSrc06
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0071 u16ScopeChSrc07
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0072 u16ScopeChAddr00
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0073 u16ScopeChAddr01
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0074 u16ScopeChAddr02
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0075 u16ScopeChAddr03
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0076 u16ScopeChAddr04
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0077 u16ScopeChAddr05
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0078 u16ScopeChAddr06
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0079 u16ScopeChAddr07
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0080 u16ScopeSampIdx
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0081 u16ScopeSampSts
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0082 _Resv82
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0083 _Resv83
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0084 _Resv84
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0085 _Resv85
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0086 _Resv86
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0087 _Resv87
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0088 _Resv88
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0089 _Resv89
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0090 _Resv90
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0091 _Resv91
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0092 _Resv92
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0093 _Resv93
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0094 _Resv94
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0095 _Resv95
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0096 _Resv96
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0097 _Resv97
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0098 _Resv98
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0099 _Resv99
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0100 _Resv100
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0101 _Resv101
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0102 _Resv102
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0103 _Resv103
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0104 _Resv104
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0105 _Resv105
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0106 _Resv106
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0107 _Resv107
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0108 _Resv108
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0109 _Resv109
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0110 _Resv110
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0111 _Resv111
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0112 _Resv112
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0113 _Resv113
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0114 _Resv114
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0115 _Resv115
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0116 _Resv116
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0117 _Resv117
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0118 _Resv118
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0119 _Resv119
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0120 _Resv120
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0121 _Resv121
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0122 _Resv122
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0123 _Resv123
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0124 _Resv124
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0125 _Resv125
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0126 _Resv126
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0127 _Resv127
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0128 _Resv128
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0129 _Resv129
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0130 _Resv130
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0131 _Resv131
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0132 _Resv132
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0133 _Resv133
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0134 _Resv134
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0135 _Resv135
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0136 _Resv136
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0137 _Resv137
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0138 _Resv138
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0139 _Resv139
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0140 _Resv140
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0141 _Resv141
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0142 _Resv142
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0143 _Resv143
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0144 _Resv144
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0145 _Resv145
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0146 _Resv146
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0147 u16UmdcHwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0148 u16UcdcHwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0149 u16Uai0HwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0150 u16Uai1HwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0151 u16Uai2HwCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0152 u16UTempHwCoeff
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0153 _Resv153
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0154 _Resv154
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0155 u16DiState
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0156 u16DoState
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0157 _Resv157
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0158 s16UaiPu0
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0159 s16UaiPu1
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0160 s16UaiPu2
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0161 _Resv161
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0162 s16UaiSi0
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0163 s16UaiSi1
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0164 s16UaiSi2
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0165 u16UaoSi0
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0166 u16UaoSi1
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0167 u16UaoSi2
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0168 _Resv168
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0169 _Resv169
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0170 u16UmdcSi
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0171 u16UcdcSi
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0172 s16TempIpmSi
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0173 s16TempRectSi
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0174 _Resv174
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0175 _Resv175
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0176 _Resv176
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0177 _Resv177
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0178 _Resv178
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0179 _Resv179
    {        W(22096),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0180 u16TunerSoftVer
    {       W(0x0303),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0181 u16TunerDrvType
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0182 _Resv182
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0183 _Resv183
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0184 _Resv184
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0185 _Resv185
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0186 _Resv186
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0187 _Resv187
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0188 _Resv188
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0189 _Resv189
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0190 _Resv190
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0191 _Resv191
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0192 _Resv192
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0193 _Resv193
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0194 _Resv194
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0195 _Resv195
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0196 _Resv196
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0197 _Resv197
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0198 _Resv198
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0199 _Resv199
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0200 _Resv200
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0201 _Resv201
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0202 _Resv202
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0203 _Resv203
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0204 _Resv204
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0205 _Resv205
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0206 u16AlmCode01
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0207 u16AlmCode02
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0208 u16AlmCode03
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0209 u16AlmCode04
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0210 u16AlmCode05
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0211 u16AlmCode06
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0212 u16AlmCode07
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0213 u16AlmCode08
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0214 u16AlmCode09
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0215 u16AlmCode10
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0216 u16AlmCode11
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0217 u16AlmCode12
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0218 u16AlmCode13
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0219 u16AlmCode14
    {            W(0),            W(0),            W(0),    B_RO |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0220 u16AlmCode15
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0221 u32AlmTime00WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0221 u32AlmTime00WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0223 u32AlmTime01WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0223 u32AlmTime01WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0225 u32AlmTime02WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0225 u32AlmTime02WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0227 u32AlmTime03WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0227 u32AlmTime03WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0229 u32AlmTime04WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0229 u32AlmTime04WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0231 u32AlmTime05WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0231 u32AlmTime05WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0233 u32AlmTime06WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0233 u32AlmTime06WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0235 u32AlmTime07WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0235 u32AlmTime07WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0237 u32AlmTime08WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0237 u32AlmTime08WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0239 u32AlmTime09WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0239 u32AlmTime09WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0241 u32AlmTime10WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0241 u32AlmTime10WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0243 u32AlmTime11WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0243 u32AlmTime11WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0245 u32AlmTime12WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0245 u32AlmTime12WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0247 u32AlmTime13WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0247 u32AlmTime13WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0249 u32AlmTime14WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0249 u32AlmTime14WH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0251 u32AlmTime15WL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0251 u32AlmTime15WH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0253 _Resv253
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0254 _Resv254
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0255 _Resv255
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0256 _Resv256
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0257 _Resv257
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0258 _Resv258
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0259 _Resv259
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0260 u16ProbeStatus
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0261 s64ProbePosEdgePo00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0261 s64ProbePosEdgePo00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0261 s64ProbePosEdgePo00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0261 s64ProbePosEdgePo00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0265 s64ProbeNegEdgePo00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0265 s64ProbeNegEdgePo00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0265 s64ProbeNegEdgePo00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0265 s64ProbeNegEdgePo00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0269 s64ProbePosEdgePo01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0269 s64ProbePosEdgePo01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0269 s64ProbePosEdgePo01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0269 s64ProbePosEdgePo01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0273 s64ProbeNegEdgePo01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0273 s64ProbeNegEdgePo01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0273 s64ProbeNegEdgePo01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0273 s64ProbeNegEdgePo01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0277 s64ProbePosEdgePo02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0277 s64ProbePosEdgePo02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0277 s64ProbePosEdgePo02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0277 s64ProbePosEdgePo02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0281 s64ProbeNegEdgePo02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0281 s64ProbeNegEdgePo02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0281 s64ProbeNegEdgePo02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0281 s64ProbeNegEdgePo02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0285 s64ProbePosEdgePo03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0285 s64ProbePosEdgePo03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0285 s64ProbePosEdgePo03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0285 s64ProbePosEdgePo03W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0289 s64ProbeNegEdgePo03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0289 s64ProbeNegEdgePo03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0289 s64ProbeNegEdgePo03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0289 s64ProbeNegEdgePo03W3
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0293 _Resv293
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0294 _Resv294
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0295 u16PosLoopIsrTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0296 u16SpdLoopIsrTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0297 u16CurLoopIsrTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0298 u16LoopTick
};

const para_attr_t sAxisAttr[] = {
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0300 _Resv300
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0301 u16MotorType
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0302 u16EncoderType
    {            W(2),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0303 u16MotPolePairs
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0304 u16MotAccMax
    {           WL(0),           WL(0),     WL(U32_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV | B_DOB0 }, // P0305 u32MotInertiaWL
    {           WH(0),           WH(0),     WH(U32_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV | B_DOB1 }, // P0305 u32MotInertiaWH
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0307 u16MotStatorRes
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0308 u16MotStatorLd
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0309 u16MotStatorLq
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0310 u16MotCurRate
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0311 u16MotCurMax
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0312 u16MotTrqRate
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0313 u16MotTrqMax
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0314 u16MotSpdRate
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0315 u16MotSpdMax
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0316 u16MotEmfCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0317 u16MotTrqCoeff
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0318 u16MotTm
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0319 _Resv319
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0320 _Resv320
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0321 _Resv321
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0322 u16PosLoopKp
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0323 u16PosLoopKi
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0324 u16PosLoopKd
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0325 u16SpdLoopKp
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0326 u16SpdLoopKi
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0327 u16SpdLoopKd
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0328 u16CurLoopIqKp
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0329 u16CurLoopIqKi
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0330 u16CurLoopIqKd
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0331 u16CurLoopIdKp
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0332 u16CurLoopIdKi
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC | B_NCOV |  B_SIG }, // P0333 u16CurLoopIdKd
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0334 _Resv334
    {         W(8000),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0335 u16CarryFreq
    {            W(0),            W(0),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0336 u16CurSampType
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0337 _Resv337
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0338 _Resv338
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0339 _Resv339
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0340 _Resv340
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0341 u16AppSel
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0342 u16CtrlMethod
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0343 u16CtrlMode
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0344 u16CtrlCmdSrc
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0345 u16PwrOnAutoRun
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0346 u16ServoOn
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0347 _Resv347
    {            W(0),            W(0),            W(1), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0348 u16DiSrc
    {            W(0),            W(0),            W(1), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0349 u16DoSrc
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0350 _Resv350
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0351 _Resv351
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0352 u16PosLimSrc
    {           W0(0),           W0(0),           W0(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0353 s64PosLimFwdW0
    {           W1(0),           W1(0),           W1(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0353 s64PosLimFwdW1
    {           W2(0),           W2(0),           W2(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0353 s64PosLimFwdW2
    {           W3(0),           W3(0),           W3(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0353 s64PosLimFwdW3
    {           W0(0),           W0(0),           W0(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0357 s64PosLimRevW0
    {           W1(0),           W1(0),           W1(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0357 s64PosLimRevW1
    {           W2(0),           W2(0),           W2(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0357 s64PosLimRevW2
    {           W3(0),           W3(0),           W3(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0357 s64PosLimRevW3
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0361 u16PosLimSts
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0362 _Resv362
    {           WL(0),           WL(0),           WL(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0363 u32ElecGearNumWL
    {           WH(0),           WH(0),           WH(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0363 u32ElecGearNumWH
    {           WL(0),           WL(0),           WL(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0365 u32ElecGearDenoWL
    {           WH(0),           WH(0),           WH(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0365 u32ElecGearDenoWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0367 _Resv367
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0368 u16EncFreqDivDir
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0369 u16EncFreqDivNum
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0370 u16EncFreqDivDeno
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0371 _Resv371
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0372 s64PosDigRef00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0372 s64PosDigRef00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0372 s64PosDigRef00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0372 s64PosDigRef00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0376 s64PosDigRef01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0376 s64PosDigRef01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0376 s64PosDigRef01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0376 s64PosDigRef01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0380 s64PosDigRef02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0380 s64PosDigRef02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0380 s64PosDigRef02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0380 s64PosDigRef02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0384 s64PosDigRef03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0384 s64PosDigRef03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0384 s64PosDigRef03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0384 s64PosDigRef03W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0388 s64PosDigRef04W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0388 s64PosDigRef04W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0388 s64PosDigRef04W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0388 s64PosDigRef04W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0392 s64PosDigRef05W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0392 s64PosDigRef05W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0392 s64PosDigRef05W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0392 s64PosDigRef05W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0396 s64PosDigRef06W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0396 s64PosDigRef06W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0396 s64PosDigRef06W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0396 s64PosDigRef06W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0400 s64PosDigRef07W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0400 s64PosDigRef07W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0400 s64PosDigRef07W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0400 s64PosDigRef07W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0404 s64PosDigRef08W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0404 s64PosDigRef08W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0404 s64PosDigRef08W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0404 s64PosDigRef08W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0408 s64PosDigRef09W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0408 s64PosDigRef09W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0408 s64PosDigRef09W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0408 s64PosDigRef09W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0412 s64PosDigRef10W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0412 s64PosDigRef10W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0412 s64PosDigRef10W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0412 s64PosDigRef10W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0416 s64PosDigRef11W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0416 s64PosDigRef11W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0416 s64PosDigRef11W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0416 s64PosDigRef11W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0420 s64PosDigRef12W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0420 s64PosDigRef12W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0420 s64PosDigRef12W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0420 s64PosDigRef12W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0424 s64PosDigRef13W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0424 s64PosDigRef13W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0424 s64PosDigRef13W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0424 s64PosDigRef13W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0428 s64PosDigRef14W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0428 s64PosDigRef14W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0428 s64PosDigRef14W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0428 s64PosDigRef14W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD0 }, // P0432 s64PosDigRef15W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD1 }, // P0432 s64PosDigRef15W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD2 }, // P0432 s64PosDigRef15W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_QUD3 }, // P0432 s64PosDigRef15W3
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0436 _Resv436
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0437 u16ProbeStatus
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0438 s64ProbePosEdgePo00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0438 s64ProbePosEdgePo00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0438 s64ProbePosEdgePo00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0438 s64ProbePosEdgePo00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0442 s64ProbeNegEdgePo00W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0442 s64ProbeNegEdgePo00W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0442 s64ProbeNegEdgePo00W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0442 s64ProbeNegEdgePo00W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0446 s64ProbePosEdgePo01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0446 s64ProbePosEdgePo01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0446 s64ProbePosEdgePo01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0446 s64ProbePosEdgePo01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0450 s64ProbeNegEdgePo01W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0450 s64ProbeNegEdgePo01W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0450 s64ProbeNegEdgePo01W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0450 s64ProbeNegEdgePo01W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0454 s64ProbePosEdgePo02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0454 s64ProbePosEdgePo02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0454 s64ProbePosEdgePo02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0454 s64ProbePosEdgePo02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0458 s64ProbeNegEdgePo02W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0458 s64ProbeNegEdgePo02W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0458 s64ProbeNegEdgePo02W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0458 s64ProbeNegEdgePo02W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0462 s64ProbePosEdgePo03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0462 s64ProbePosEdgePo03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0462 s64ProbePosEdgePo03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0462 s64ProbePosEdgePo03W3
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0466 s64ProbeNegEdgePo03W0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0466 s64ProbeNegEdgePo03W1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0466 s64ProbeNegEdgePo03W2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0466 s64ProbeNegEdgePo03W3
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0470 _Resv470
    {            W(0),            W(0),            W(1), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0471 u16SpdRefSrc
    {           WL(0),           WL(0),           WL(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0472 s32SpdDigRefWL
    {           WH(0),           WH(0),           WH(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0472 s32SpdDigRefWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0474 _Resv474
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0475 u16AccTime
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0476 u16DecTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0477 _Resv477
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0478 u16JogDigRef
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0479 u16JogAccDecTime
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0480 _Resv480
    {            W(0),            W(0),            W(0), B_RW_M2 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0481 u16SpdLimSrc
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0482 u16SpdLimFwd
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0483 u16SpdLimRev
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0484 u16SpdLimSts
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0485 _Resv485
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0486 u16AiSpdCoeff00
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0487 u16AiSpdCoeff01
    {            W(0),            W(0),            W(0), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0488 u16AiSpdCoeff02
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0489 _Resv489
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0490 _Resv490
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0491 _Resv491
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0492 _Resv492
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0493 _Resv493
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0494 _Resv494
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0495 _Resv495
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0496 _Resv496
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0497 s32SpdDigRef00WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0497 s32SpdDigRef00WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0499 s32SpdDigRef01WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0499 s32SpdDigRef01WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0501 s32SpdDigRef02WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0501 s32SpdDigRef02WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0503 s32SpdDigRef03WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0503 s32SpdDigRef03WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0505 s32SpdDigRef04WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0505 s32SpdDigRef04WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0507 s32SpdDigRef05WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0507 s32SpdDigRef05WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0509 s32SpdDigRef06WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0509 s32SpdDigRef06WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0511 s32SpdDigRef07WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0511 s32SpdDigRef07WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0513 s32SpdDigRef08WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0513 s32SpdDigRef08WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0515 s32SpdDigRef09WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0515 s32SpdDigRef09WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0517 s32SpdDigRef10WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0517 s32SpdDigRef10WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0519 s32SpdDigRef11WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0519 s32SpdDigRef11WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0521 s32SpdDigRef12WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0521 s32SpdDigRef12WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0523 s32SpdDigRef13WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0523 s32SpdDigRef13WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0525 s32SpdDigRef14WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0525 s32SpdDigRef14WH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB0 }, // P0527 s32SpdDigRef15WL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV | B_DOB1 }, // P0527 s32SpdDigRef15WH
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0529 u16AccTime00
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0530 u16AccTime01
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0531 u16AccTime02
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0532 u16AccTime03
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0533 u16AccTime04
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0534 u16AccTime05
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0535 u16AccTime06
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0536 u16AccTime07
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0537 u16AccTime08
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0538 u16AccTime09
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0539 u16AccTime10
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0540 u16AccTime11
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0541 u16AccTime12
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0542 u16AccTime13
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0543 u16AccTime14
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0544 u16AccTime15
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0545 u16DecTime00
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0546 u16DecTime01
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0547 u16DecTime02
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0548 u16DecTime03
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0549 u16DecTime04
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0550 u16DecTime05
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0551 u16DecTime06
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0552 u16DecTime07
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0553 u16DecTime08
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0554 u16DecTime09
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0555 u16DecTime10
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0556 u16DecTime11
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0557 u16DecTime12
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0558 u16DecTime13
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0559 u16DecTime14
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0560 u16DecTime15
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0561 _Resv561
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0562 _Resv562
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0563 _Resv563
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0564 _Resv564
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0565 _Resv565
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0566 _Resv566
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0567 _Resv567
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0568 _Resv568
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0569 _Resv569
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0570 _Resv570
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0571 _Resv571
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0572 _Resv572
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0573 _Resv573
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0574 _Resv574
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0575 _Resv575
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0576 _Resv576
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0577 _Resv577
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0578 _Resv578
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0579 _Resv579
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0580 _Resv580
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0581 _Resv581
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0582 _Resv582
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0583 _Resv583
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0584 _Resv584
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0585 _Resv585
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0586 s16TrqDigRef00
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0587 s16TrqDigRef01
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0588 s16TrqDigRef02
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0589 s16TrqDigRef03
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0590 s16TrqDigRef04
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0591 s16TrqDigRef05
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0592 s16TrqDigRef06
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0593 s16TrqDigRef07
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0594 s16TrqDigRef08
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0595 s16TrqDigRef09
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0596 s16TrqDigRef10
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0597 s16TrqDigRef11
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0598 s16TrqDigRef12
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0599 s16TrqDigRef13
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0600 s16TrqDigRef14
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR |  B_SYNC |  B_COV |  B_SIG }, // P0601 s16TrqDigRef15
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0602 _Resv602
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0603 _Resv603
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0604 _Resv604
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0605 _Resv605
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0606 _Resv606
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0607 _Resv607
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0608 _Resv608
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0609 _Resv609
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0610 _Resv610
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0611 _Resv611
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0612 _Resv612
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0613 s32DrvSpdRefWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0613 s32DrvSpdRefWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0615 s32DrvSpdFbWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0615 s32DrvSpdFbWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0617 _Resv617
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0618 _Resv618
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0619 _Resv619
    {            W(0),      W(U16_MIN),      W(U16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0620 u16ElecAngle
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0621 _Resv621
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0622 _Resv622
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0623 _Resv623
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0624 _Resv624
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0625 s16Ud
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0626 s16Uq
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0627 s16Ualpha
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0628 s16Ubeta
    {            W(0),            W(0),            W(7),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0629 u16Sector
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0630 u16PwmaComp
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0631 u16PwmbComp
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0632 u16PwmcComp
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0633 _Resv633
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0634 _Resv634
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0635 _Resv635
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0636 _Resv636
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0637 _Resv637
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0638 _Resv638
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0639 _Resv639
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0640 s16IaFbSi
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0641 s16IbFbSi
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0642 s16IcFbSi
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0643 _Resv643
    {           W0(0),           W0(0),           W0(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0644 s64UserPosRefW0
    {           W1(0),           W1(0),           W1(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0644 s64UserPosRefW1
    {           W2(0),           W2(0),           W2(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0644 s64UserPosRefW2
    {           W3(0),           W3(0),           W3(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0644 s64UserPosRefW3
    {           W0(0),           W0(0),           W0(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD0 }, // P0648 s64UserPosFbW0
    {           W1(0),           W1(0),           W1(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD1 }, // P0648 s64UserPosFbW1
    {           W2(0),           W2(0),           W2(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD2 }, // P0648 s64UserPosFbW2
    {           W3(0),           W3(0),           W3(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_QUD3 }, // P0648 s64UserPosFbW3
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0652 s32UserSpdRefWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0652 s32UserSpdRefWH
    {           WL(0),           WL(0),           WL(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB0 }, // P0654 s32UserSpdFbWL
    {           WH(0),           WH(0),           WH(0),    B_RO |    B_NR | B_NSYNC | B_NCOV | B_DOB1 }, // P0654 s32UserSpdFbWH
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0656 s16UserTrqRef
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0657 s16UserTrqFb
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0658 _Resv658
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0659 _Resv659
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0660 _Resv660
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0661 _Resv661
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0662 _Resv662
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0663 _Resv663
    {            W(0),            W(0),            W(0),    B_RO |    B_NR | B_NSYNC | B_NCOV |  B_SIG }, // P0664 _Resv664
};
// clang-format on
