#ifndef __PINMAP_H__
#define __PINMAP_H__

#define BOARD_AT32F415CB_DEV

#define LED1_PIN       GPIOF, GPIO_PINS_6
#define LED2_PIN       GPIOF, GPIO_PINS_7
#define BUTTON_PIN     GPIOA, GPIO_PINS_0

#define EEPROM_SCL_PIN GPIOB, GPIO_PINS_6
#define EEPROM_SDA_PIN GPIOB, GPIO_PINS_7

#endif
